### ISSUE TITLE
Analyzing doe?

### ISSUE THREAD

**Issue by matalab** [tirthajyoti/doepy#6]
Hello,
Once doe is generated and results acquired, how to analyze results?
Do you have plans to integrate corresponding statistical analysis tools (such as ANOVA, regression etc.) into the doepy or can you advise which respective python libraries to use for results analysis?

**Comment by tirthajyoti** [comment]
Use `Scipy` or `statsmodels` for any such standard analysis.

For linear regression, I have written a small and lightweight package called `MLR`. You can try it. [Read the docs here](https://mlr.readthedocs.io/en/latest/).
